require 'rspec/webservice_matchers/have_a_valid_cert'
require 'rspec/webservice_matchers/redirect_permanently_to'
require 'rspec/webservice_matchers/redirect_temporarily_to'
require 'rspec/webservice_matchers/enforce_https_everywhere'
require 'rspec/webservice_matchers/be_status'
require 'rspec/webservice_matchers/be_up'
require 'rspec/webservice_matchers/be_fast'
